### ISSUE TITLE
Where are the tools?

### ISSUE THREAD

**Issue by bfontaine** [UniqMartin/homebrew-tools#1]
Did you forgot to push the tools? :smile: 

Also if you have some handy custom commands (I saw `brew-report` in a PR) you might want to import them into https://github.com/Homebrew/homebrew-dev-tools.

**Comment by UniqMartin** [comment]
> Did you forgot to push the tools? :smile:

Not really. I wanted to iron out a few issues before making them public … and then I got stuck.

> Also if you have some handy custom commands (I saw `brew report` in a PR) you might want to import them into https://github.com/Homebrew/homebrew-dev-tools.

I didn't even dream of being a Homebrew maintainer when I created this repository. :smiley_cat: I'll make sure to let you (and the others) know once I believe to have something useful; and import it if you feel the same.
